### ISSUE TITLE
Avoid showing up automatically generated fields for initialization by start attributes in the Generator parameter input window

### ISSUE THREAD

**Issue by ceraolo** [PowerGrids/PowerGrids#155]
This issue relates to branch "Develop" as in 19th of September 2024.

In the synchronous generator user mask (e.g. in ENTSOE.SteadyState.GEN). initialisation compares both in the General and inthe Initialization tabs (screenshots below).
This is a bit confusing. Wouldn't be better to put all the initializations in the initialization tab?

![image](https://github.com/user-attachments/assets/88284478-f027-4d6b-8864-7db8c2d47f2f)

![image](https://github.com/user-attachments/assets/f921c71d-2410-4f11-86be-9a9bef07c456)

**Comment by casella** [comment]
@ceraolo, thanks for reporting. 

That initialization group is generated automatically by the GUI, because there are explicit start modifier. This is a mechanism that is used to handle initial equations with fixed attributes, e.g. in the Modelica MultiBody library.

I think this should be easilty solved by making those bindings `final`, so they cannot be changed upon instantiation. The idea is that these start values are managed by means of the bound parameters, e.g. `uPuStart`. 

@AndreaBartolini do you agree?

**Comment by AndreaBartolini** [comment]
If the proposed solution (to make the bindings `final`) works fine, there are no caveats from my side.

**Comment by casella** [comment]
Just bear in mind that we'll get the desired outcome whtn ticket OpenModelica/OpenModelica#12898 is fixed 😅

**Comment by casella** [comment]
Everything should be fixed now both on the source code front and on the OMEdit front. I'll check that ASAP.

**Comment by AndreaBartolini** [comment]
some problems are still present here, as depicted in https://github.com/OpenModelica/OpenModelica/issues/12898

**Comment by AndreaBartolini** [comment]
Fixed by PR #203
